package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-11-30T14:22:21.903+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "Service1", 
                  wsdlLocation = "file:/C:/workspace/nashclient/src/main/resources/Service1.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class Service1 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "Service1");
    public final static QName BasicHttpBindingIPokerService = new QName("http://tempuri.org/", "BasicHttpBinding_IPokerService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace/nashclient/src/main/resources/Service1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Service1.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/nashclient/src/main/resources/Service1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Service1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service1() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Service1(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Service1(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Service1(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IPokerService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPokerService")
    public IPokerService getBasicHttpBindingIPokerService() {
        return super.getPort(BasicHttpBindingIPokerService, IPokerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPokerService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPokerService")
    public IPokerService getBasicHttpBindingIPokerService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIPokerService, IPokerService.class, features);
    }

}
